#pragma once
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by builtins.rc
//
#define IDD_DIALOG1                     101
#define IDD_UNKNOWN                     101
#define IDD_ABOUT                       102
#define IDD_EPALOGO                     103
#define IDD_SYSBIOS_MAIN                104
#define IDD_SYSBIOS                     105
#define IDD_SYSBIOS_DRIVE_TABLE         106
#define IDD_SYSBIOS_CHIPSET_REGS        107
#define IDD_SYSBIOS_TIMINGS             108
#define IDD_SYSBIOS_BIOS_OPTIONS        109
#define IDD_SYSBIOS_CONFIG_MENU         111
#define IDD_SYSBIOS_IRQ_ROUTING         112
#define IDD_SYSBIOS_VER_DIFF            113
#define IDR_DRIVE_TABLE                 114
#define IDR_NODRIVE_TABLE               115
#define IDD_MODIFY_DRIVE                116
#define IDR_CHIPSET_TABLE               117
#define IDR_NOCHIPSET_TABLE             118
#define IDD_MODIFY_CHIPSET              119
#define IDR_ROUTING_TABLE               120
#define IDR_NOROUTING_TABLE             121
#define IDD_MODIFY_ROUTING              122
#define IDC_EPA_WIDTH                   1000
#define IDC_EPA_HEIGHT                  1001
#define IDC_EPA_VERSION                 1002
#define IDC_EPA_EXPORT                  1003
#define IDC_SYSBIOS_ID                  1004
#define IDC_SYSBIOS_MESSAGE             1005
#define IDC_SYSBIOS_VERSION             1006
#define IDC_SYSBIOS_INFO                1008
#define IDC_TEXT_SYSBIOS_VERSION        1009
#define IDC_TEXT_SYSBIOS_INFO           1010
#define IDC_TEXT_SYSBIOS_MESSAGE        1011
#define IDC_TEXT_SYSBIOS_ID             1012
#define IDC_SYSBIOS_TABCTRL             1016
#define IDC_DRIVE_LIST                  1019
#define IDC_CHIPSET_REGS                1020
#define IDC_SYSBIOS_REFRESHRATE         1022
#define IDC_SYSBIOS_FDDMOTORSPINUP      1023
#define IDC_SYSBIOS_FDDHEADSETTLE       1024
#define IDC_SYSBIOS_LPTINITIALIZE       1025
#define IDC_SYSBIOS_KEYBOARDCHECK       1026
#define IDC_SYSBIOS_FDCIRQ6COMPLETION   1027
#define IDC_SYSBIOS_FDCSTATUSBYTEREAD   1028
#define IDC_SYSBIOS_FDCCOMMANDBYTESEND  1029
#define IDC_SYSBIOS_HDCBUSYCHECK        1030
#define IDC_SYSBIOS_HDCIRQ14COMPLETION  1031
#define IDC_SYSBIOS_HDCDATAREQUEST      1032
#define IDC_SYSBIOS_COMPORTTIMEOUT      1033
#define IDC_SYSBIOS_LPTBUSYCHECK        1034
#define IDC_SYSBIOS_BOOTUP_NUMLOCK      1035
#define IDC_SYSBIOS_FLOPPY_SPEEDSWITCH  1036
#define IDC_SYSBIOS_FLOPPY_PIEWAIT      1037
#define IDC_SYSBIOS_COLOR_OPTSETUP      1038
#define IDC_SYSBIOS_COLOR_OPTPOST       1039
#define IDC_SYSBIOS_BOOTUP_DISPPCICONF  1040
#define IDC_SYSBIOS_BOOTUP_POWERONDELAY 1041
#define IDC_SYSBIOS_COLOR_SETUPDEFAULT  1042
#define IDC_SYSBIOS_COLOR_POSTDEFAULT   1043
#define IDC_SYSBIOS_SECURITY_PASSWORD   1044
#define IDC_SYSBIOS_SECURITY_NUMRETRIES 1045
#define IDC_SYSBIOS_MISC_DRAMPARITY     1046
#define IDC_SYSBIOS_BOOTUP_KEYLOCK      1047
#define IDC_SYSBIOS_VIDEO_ROME000       1048
#define IDC_SYSBIOS_VIDEO_ROMC000       1049
#define IDC_SYSBIOS_MISC_LOOPCHECK      1050
#define IDC_SYSBIOS_BOOTUP_PS2MOUSE     1051
#define IDC_MENU_TREE                   1052
#define IDC_MENU_HEADER                 1053
#define IDC_MENU_HELP                   1054
#define IDC_MENU_STATUS                 1058
#define IDC_MENU_ACTIVE                 1059
#define IDC_MENU_SHOWONLY               1060
#define IDC_MENU_DISABLED               1061
#define IDC_MENU_POSITION_X             1062
#define IDC_MENU_POSITION_Y             1063
#define IDC_MENU_CMOS_INDEX             1066
#define IDC_MENU_RUN                    1067
#define IDC_MENU_CMOS_MASK              1068
#define IDC_MENU_CHIPREG_INDEX          1069
#define IDC_MENU_CHIPREG_MASK           1070
#define IDC_IRQ_ROUTING                 1071
#define IDC_CHECKSUM_RANGE_START        1072
#define IDC_CHECKSUM_RANGE_END          1073
#define IDC_CHECKSUM_METHOD_ADD         1074
#define IDC_CHECKSUM_METHOD_SUB         1075
#define IDC_CHECKSUM_VALUE              1076
#define IDC_CHECKSUM_RECALC             1077
#define IDC_CHECKSUM_RESULT             1078
#define IDC_VER_PREV                    1079
#define IDC_VER_CURR                    1080
#define IDC_MODIFY_TYPE                 1080
#define IDC_MODIFY_CYL                  1081
#define IDC_MODIFY_HEADS                1082
#define IDC_MODIFY_PRECOMP              1083
#define IDC_MODIFY_CONTROL              1084
#define IDC_MODIFY_LZONE                1085
#define IDC_MODIFY_SECTORS              1086
#define IDC_MODIFY_INDEX                1087
#define IDC_MODIFY_DEVICE               1088
#define IDC_MODIFY_FUNC                 1089
#define IDC_MODIFY_MASK                 1090
#define IDC_MODIFY_VALUE                1091
#define IDC_MODIFY_MAP                  1092
#define IDC_MODIFY_SLOT                 1093
#define IDC_MODIFY_IRQ                  1094
#define IDC_MODIFY_INTA                 1095
#define IDC_MODIFY_INTB                 1096
#define IDC_MODIFY_INTC                 1097
#define IDC_MODIFY_INTD                 1098
#define IDC_MENU_ITEMSETUP              1099
#define IDC_MENU_ITEMBIOS               1100
#define IDC_MENU_EDITITEMS              1101
#define IDC_TEXT_COMPILETIME            1102
#define IDC_FILENAME                    30000
#define IDC_FILE_ID                     30001
#define IDC_FILE_SIZE                   30002
#define IDC_FILE_OFFSET                 30003
#define ID_DRVTBL_MODIFY                40001
#define ID_DRVTBL_CLEAR                 40002
#define ID_DRVTBL_CLEARALL              40003
#define ID_MENUITEM40004                40004
#define ID_CHIPSET_MODIFY               40005
#define ID_CHIPSET_RELOC                40006
#define ID_MENUITEM40007                40007
#define ID_ROUTING_MODIFY               40008
#define ID_MENUITEM40009                40009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
